apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexvion-ingress
  namespace: nexvion-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nexvion.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexvion-service
            port:
              number: 80
