pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'nusradotnet/nexvion-web'
        BUILD_TAG    = "${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }
        stage('Security Scan') {
            steps {
                echo '=== Running Trivy Secret Scan ==='
                sh 'docker run --rm -v $(pwd):/root/src aquasec/trivy fs /root/src'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t ${DOCKER_IMAGE}:${BUILD_TAG} -f docker/Dockerfile .'
            }
        }
        stage('Image Vulnerability Scan') {
            steps {
                echo '=== Running Container Image Scan ==='
                sh 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image ${DOCKER_IMAGE}:${BUILD_TAG}'
            }
        }
        stage('Deploy & Rollout') {
            steps {
                sh 'kubectl apply -f k8s/ -n nexvion-ns'
                sh 'kubectl rollout status deployment/nexvion-deployment -n nexvion-ns'
            }
        }
    }
}
